"""Library for managing reference docs — living explanations of how the system works.

Built on the shared ``core`` mechanics; supplies the reference-doc schema (6-digit ids,
``ref-meta`` markers, created/updated/related fields) and the ``updated >= created`` rule.
Unlike ADRs, reference docs have no proposed/accepted/superseded lifecycle — they are edited
in place.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

import core
from core import load_tags  # re-exported unchanged

# Ordered reference-doc metadata fields mapped to their human-readable table labels.
FIELD_LABELS: dict[str, str] = {
    "id": "ID",
    "title": "Title",
    "description": "Description",
    "tags": "Tags",
    "created": "Created",
    "updated": "Updated",
    "related": "Related",
}

LIST_FIELDS = {"tags", "related"}

META_START = "<!-- ref-meta:start -->"
META_END = "<!-- ref-meta:end -->"

WIDTH = 6
INDEX_NAME = "README.md"
_INDEX_COMMAND = "./scripts/ref index"

__all__ = ["load_tags"]  # silence unused-import lint for the re-export


def parse_doc(path) -> core.Doc:
    return core.parse_doc(path)


def dump_frontmatter(fm: dict) -> str:
    return core.dump_frontmatter(fm, FIELD_LABELS)


def display_value(field_name: str, value) -> str:
    return core.display_value(value, field_name in LIST_FIELDS)


def render_meta_table(fm: dict) -> str:
    return core.render_meta_table(fm, FIELD_LABELS, LIST_FIELDS, META_START, META_END)


def extract_meta_table(body: str) -> str | None:
    return core.extract_meta_table(body, META_START, META_END)


def next_id(ref_dir) -> str:
    return core.next_id(ref_dir, WIDTH)


def iter_docs(ref_dir) -> list[core.Doc]:
    return core.iter_docs(ref_dir, WIDTH)


def render_index(docs: list[core.Doc]) -> str:
    lines = [
        "# Reference Docs",
        "",
        "Generated by `./scripts/ref index` — do not edit by hand.",
        "",
        "| ID | Title | Tags |",
        "| --- | --- | --- |",
    ]
    for d in docs:
        fm = d.frontmatter
        link = f"[{fm.get('id', '?')}]({d.path.name})"
        tags_cell = display_value("tags", fm.get("tags"))
        lines.append(f"| {link} | {fm.get('title', '')} | {tags_cell} |")
    return "\n".join(lines) + "\n"


def _date_check(doc: core.Doc) -> list[str]:
    created = doc.frontmatter.get("created")
    updated = doc.frontmatter.get("updated")
    if not created or not updated:
        return []
    try:
        created_date = date.fromisoformat(str(created))
        updated_date = date.fromisoformat(str(updated))
    except ValueError:
        return [f"{doc.path.name}: created/updated must be YYYY-MM-DD dates"]
    if updated_date < created_date:
        return [f"{doc.path.name}: updated ({updated}) is before created ({created})"]
    return []


def validate_docs(ref_dir) -> list[str]:
    """Return a list of human-readable validation errors (empty == valid)."""
    return core.validate_common(
        ref_dir,
        width=WIDTH,
        noun="reference doc",
        field_labels=FIELD_LABELS,
        list_fields=LIST_FIELDS,
        meta_start=META_START,
        meta_end=META_END,
        index_name=INDEX_NAME,
        index_command=_INDEX_COMMAND,
        render_index=render_index,
        per_doc_extra=_date_check,
    )


def _compose(fm: dict, body_sections: str) -> str:
    return (
        f"---\n{dump_frontmatter(fm)}\n---\n"
        f"# {fm['title']}\n\n"
        f"{render_meta_table(fm)}\n\n"
        f"{body_sections}"
    )


def new_doc(ref_dir, title: str, tags: list[str], today: str | None = None) -> Path:
    ref_dir = Path(ref_dir)
    today = today or core.today_iso()
    doc_id = next_id(ref_dir)
    fm = {
        "id": doc_id,
        "title": title,
        "description": "",
        # Tags are stored alphabetically (see _tags.md).
        "tags": sorted(tags),
        "created": today,
        "updated": today,
        "related": [],
    }

    template_path = ref_dir / "_template.md"
    if not template_path.exists():
        raise ValueError(f"reference template not found: {template_path}")
    template = parse_doc(template_path)
    meta_end_pos = template.body.find(META_END)
    if meta_end_pos != -1:
        body_sections = template.body[meta_end_pos + len(META_END) :].lstrip("\n")
    else:
        body_sections = template.body

    path = ref_dir / f"{doc_id}-{core.slugify(title)}.md"
    path.write_text(_compose(fm, body_sections), encoding="utf-8")
    return path


def add_tag(tags_path, tag: str, description: str) -> None:
    core.add_tag(tags_path, tag, description)


def write_index(ref_dir) -> None:
    core.write_index(ref_dir, INDEX_NAME, render_index, WIDTH)
