"""Library for managing Architecture Decision Records (ADRs).

Generic, schema-agnostic document mechanics live in ``core``. This module supplies the ADR
schema, the proposed→accepted lifecycle, and ADR-specific index/validation, adapting ``core``
so the historical ADR public surface (one-arg helpers, ADR-worded errors) is unchanged.
"""

from __future__ import annotations

from pathlib import Path

import core
from core import Doc as Adr  # an ADR is a Doc with the same (path, frontmatter, body) fields
from core import load_tags, slugify  # re-exported unchanged

# Ordered ADR metadata fields mapped to their human-readable table labels.
FIELD_LABELS: dict[str, str] = {
    "id": "ID",
    "name": "Name",
    "description": "Description",
    "status": "Status",
    "date_proposed": "Date proposed",
    "date_accepted": "Date accepted",
    "date_invalidated": "Date invalidated",
    "author": "Author",
    "supersedes": "Supersedes",
    "superseded_by": "Superseded by",
    "tags": "Tags",
}

VALID_STATUSES = {"proposed", "accepted", "superseded", "deprecated", "rejected"}
LIST_FIELDS = {"supersedes", "superseded_by", "tags"}

META_START = "<!-- adr-meta:start -->"
META_END = "<!-- adr-meta:end -->"
EMPTY_DISPLAY = core.EMPTY_DISPLAY

_WIDTH = 4
_INDEX_NAME = "README.md"
_INDEX_COMMAND = "./scripts/adr index"

__all__ = ["slugify", "load_tags", "Adr"]  # silence unused-import lint for re-exports


def parse_adr(path) -> Adr:
    return core.parse_doc(path)


def dump_frontmatter(fm: dict) -> str:
    return core.dump_frontmatter(fm, FIELD_LABELS)


def display_value(field_name: str, value) -> str:
    return core.display_value(value, field_name in LIST_FIELDS)


def render_meta_table(fm: dict) -> str:
    return core.render_meta_table(fm, FIELD_LABELS, LIST_FIELDS, META_START, META_END)


def extract_meta_table(body: str) -> str | None:
    return core.extract_meta_table(body, META_START, META_END)


def next_id(adr_dir) -> str:
    return core.next_id(adr_dir, _WIDTH)


def iter_adrs(adr_dir) -> list[Adr]:
    return core.iter_docs(adr_dir, _WIDTH)


def _today_iso() -> str:
    return core.today_iso()


def render_index(adrs: list[Adr]) -> str:
    lines = [
        "# Architecture Decision Records",
        "",
        "Generated by `./scripts/adr index` — do not edit by hand.",
        "",
        "| ID | Name | Status | Tags |",
        "| --- | --- | --- | --- |",
    ]
    for a in adrs:
        fm = a.frontmatter
        link = f"[{fm.get('id', '?')}]({a.path.name})"
        lines.append(
            f"| {link} | {fm.get('name', '')} | {fm.get('status', '')} "
            f"| {display_value('tags', fm.get('tags'))} |"
        )
    return "\n".join(lines) + "\n"


def _status_check(adr: Adr) -> list[str]:
    status = adr.frontmatter.get("status")
    if status not in VALID_STATUSES:
        return [f"{adr.path.name}: invalid status '{status}'"]
    return []


def validate_adrs(adr_dir) -> list[str]:
    """Return a list of human-readable validation errors (empty == valid)."""
    return core.validate_common(
        adr_dir,
        width=_WIDTH,
        noun="ADR",
        field_labels=FIELD_LABELS,
        list_fields=LIST_FIELDS,
        meta_start=META_START,
        meta_end=META_END,
        index_name=_INDEX_NAME,
        index_command=_INDEX_COMMAND,
        render_index=render_index,
        per_doc_extra=_status_check,
    )


def compose_adr(fm: dict, body_sections: str) -> str:
    """Build full ADR text: frontmatter + title + meta table + sections."""
    return (
        f"---\n{dump_frontmatter(fm)}\n---\n"
        f"# ADR-{fm['id']}: {fm['name']}\n\n"
        f"{render_meta_table(fm)}\n\n"
        f"{body_sections}"
    )


def new_adr(adr_dir, name: str, tags: list[str], author: str, today: str | None = None) -> Path:
    adr_dir = Path(adr_dir)
    today = today or _today_iso()
    adr_id = next_id(adr_dir)
    fm = {
        "id": adr_id,
        "name": name,
        "description": "",
        "status": "proposed",
        "date_proposed": today,
        "date_accepted": None,
        "date_invalidated": None,
        "author": author,
        "supersedes": [],
        "superseded_by": [],
        # Tags are stored alphabetically (see _tags.md / ADR-0001 rule 8).
        "tags": sorted(tags),
    }

    # Read body sections from _template.md (single source of truth).
    template_path = adr_dir / "_template.md"
    if not template_path.exists():
        raise ValueError(f"ADR template not found: {template_path}")
    template = parse_adr(template_path)
    meta_end_pos = template.body.find(META_END)
    if meta_end_pos != -1:
        body_sections = template.body[meta_end_pos + len(META_END) :].lstrip("\n")
    else:
        body_sections = template.body

    path = adr_dir / f"{adr_id}-{slugify(name)}.md"
    path.write_text(compose_adr(fm, body_sections), encoding="utf-8")
    return path


def _rewrite_with_synced_table(adr: Adr) -> None:
    """Persist an ADR re-rendering frontmatter + meta table, preserving sections."""
    table = extract_meta_table(adr.body)
    if table is not None:
        new_body = adr.body.replace(table, render_meta_table(adr.frontmatter), 1)
    else:
        new_body = f"{render_meta_table(adr.frontmatter)}\n\n{adr.body}"
    adr.path.write_text(
        f"---\n{dump_frontmatter(adr.frontmatter)}\n---\n{new_body}", encoding="utf-8"
    )


def accept_adr(path, today: str | None = None) -> None:
    adr = parse_adr(path)
    status = adr.frontmatter.get("status")
    if status != "proposed":
        raise ValueError(
            f"cannot accept ADR with status '{status}' (only 'proposed' ADRs can be accepted)"
        )
    adr.frontmatter["status"] = "accepted"
    adr.frontmatter["date_accepted"] = today or _today_iso()
    _rewrite_with_synced_table(adr)


def add_tag(tags_path, tag: str, description: str) -> None:
    core.add_tag(tags_path, tag, description)


def write_index(adr_dir) -> None:
    core.write_index(adr_dir, _INDEX_NAME, render_index, _WIDTH)
